export const GAME_START = "GAME_START";
export const GAME_FINISH = "GAME_FINISH";
export const UPDATE_GAME_HISTORY = "UPDATE_GAME_HISTORY";
export const GAME_SELECTED_WEAPON = "GAME_SELECTED_WEAPON";
export const GAME_CHANGE_MODE = "GAME_CHANGE_MODE";